name: Create License

on:
  repository_dispatch:
    types: [create_license]

jobs:
  generate_license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create License File
        run: |
          echo "LICENSE=OK" > licenses/${{ github.event.client_payload.form_email }}.txt
          
      - name: Push License File
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add licenses/
          git commit -m "Add license for ${{ github.event.client_payload.form_email }}"
          git push
