name: Auto‑Delete License Files After 3 Hours

on:
  schedule:
    - cron: '0 * * * *'    # runs every hour
  workflow_dispatch:      # manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      # important—get full commit history

      - name: Debug: show files & commit dates
        run: |
          THRESHOLD=$(date -d '3 hours ago' +%s)
          echo "Threshold (3h ago): $THRESHOLD"
          echo "All .txt files and their last commit timestamps:"
          for f in *.txt; do
            [ -f "$f" ] || continue
            CT=$(git log -1 --format=%ct -- "$f")
            echo "  $f → $CT"
          done

      - name: Delete old license files
        run: |
          THRESHOLD=$(date -d '3 hours ago' +%s)
          for f in *.txt; do
            [ -f "$f" ] || continue
            CT=$(git log -1 --format=%ct -- "$f")
            if [ "$CT" -lt "$THRESHOLD" ]; then
              echo "Deleting $f (last commit $CT)"
              rm "$f"
            fi
          done

      - name: Commit & push deletions
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A                          # stage deletions too
          git commit -m "Auto‑delete license files older than 3h" || echo "No files to delete"
          git push                            # push only if commit succeeded
