name: Auto‑Delete License Files After 3 Hours

on:
  schedule:
    - cron: '0 * * * *'    # runs hourly
  workflow_dispatch:      # manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete license files older than 3 hours by commit date
        run: |
          # Compute threshold: UNIX timestamp for 3 hours ago
          THRESHOLD=$(date -d '3 hours ago' +%s)
          echo "Threshold (3h ago): $THRESHOLD"

          # Iterate over each .txt in the root
          for file in *.txt; do
            [ -f "$file" ] || continue
            # Get the last commit timestamp for this file
            CT=$(git log -1 --format=%ct -- "$file")
            echo "$file last committed at $CT"

            # If that commit is older than our threshold, delete it
            if [ "$CT" -lt "$THRESHOLD" ]; then
              echo "Deleting $file"
              rm "$file"
            fi
          done

      - name: Commit & push deletions
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Auto‑delete license files older than 3 hours'
          add: '*.txt'
