name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Your build steps (for example, if you're building a static site)
      - name: Build site
        run: |
          # Your build commands here (e.g., npm install, npm run build)
          echo "Building site"

      # Upload artifact with a unique name
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-artifact  # Ensure this name is unique
          path: ./path-to-your-artifact # Replace with your build output

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after the build job

    steps:
      - name: Checkout code again
        uses: actions/checkout@v3

      # Deploy to GitHub Pages using the uploaded artifact
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-artifact  # Must match the upload name
